import module
result_add = module.add(30,30)
result_sub = module.sub(30,30)
calc=module.Calculator()
result_mul=calc.mul(30,30)
result_div=calc.div(30,0)
print(result_add)
print(result_sub)
print(result_mul)
print(result_div)